server.port: 8766
spring:
    datasource:
        name: test
        url: jdbc:mysql://192.168.138.128:3306/test??useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456

mybatis:
  mapperLocations: classpath:mapper/*.xml